version: "3"
services:
  modular-monolith-autoheal:
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_INTERVAL=30
      - AUTOHEAL_CONTAINER_LABEL=all    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  modular-monolith-database:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: P@ssword1
    ports:
      - 3000:1433
    expose:
      - 1433
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "P@ssword1", "-Q", "SELECT 1"]
      retries: 5
  modular-monolith-database-setup:
    build:
      context: "."
      dockerfile: "./docker/configuration/dotnet/Dockerfile"
      args:
        PROJECT_PATH: Example/ModularMonolith.Database
        ASSEMBLY_NAME: ModularMonolith.Database
    restart: on-failure
    depends_on:
      - "modular-monolith-database"
    environment:
      - ConnectionStrings__Database=Data Source=modular-monolith-database;Initial Catalog=Hexure;Connection Timeout=30;User Id=sa;Password=P@ssword1;MultipleActiveResultSets=False;Timeout=30;
  modular-monolith-rabbitmq:
    image: "rabbitmq:3-management"
    volumes:
      - ./docker/configuration/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./docker/configuration/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - ./docker/configuration/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    ports:
      - 3001:5672
      - 3002:15672
    expose:
      - 5672
      - 15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      retries: 5
  modular-monolith-identity:
    build:
      context: "."
      dockerfile: "./docker/configuration/dotnet-api/Dockerfile"
      args:
        PROJECT_PATH: Example/IdentityServer
        ASSEMBLY_NAME: IdentityServer
    restart: on-failure
    environment:
      - Issuer__Url=http://modular-monolith-identity
    ports:
      - 3003:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://modular-monolith-identity/.well-known/openid-configuration"]
      retries: 5
  modular-monolith-events-publisher:
    build:
      context: "."
      dockerfile: "./docker/configuration/dotnet-api/Dockerfile"
      args:
        PROJECT_PATH: Example/ModularMonolith.EventsPublisher
        ASSEMBLY_NAME: ModularMonolith.EventsPublisher
    restart: on-failure
    depends_on:
      - "modular-monolith-database"
      - "modular-monolith-rabbitmq"
    environment:
      - ConnectionStrings__Database=Data Source=modular-monolith-database;Initial Catalog=Hexure;Connection Timeout=30;User Id=sa;Password=P@ssword1;MultipleActiveResultSets=False;Timeout=30;
      - Bus__Host=rabbitmq://modular-monolith-rabbitmq
      - ASPNETCORE_URLS=http://+:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://modular-monolith-events-publisher/api/health-check"]
      retries: 5
  modular-monolith-events-consumer:
    build:
      context: "."
      dockerfile: "./docker/configuration/dotnet-api/Dockerfile"
      args:
        PROJECT_PATH: Example/ModularMonolith.EventsConsumer
        ASSEMBLY_NAME: ModularMonolith.EventsConsumer
    restart: on-failure
    depends_on:
      - "modular-monolith-database"
      - "modular-monolith-rabbitmq"
    environment:
      - ConnectionStrings__Database=Data Source=modular-monolith-database;Initial Catalog=Hexure;Connection Timeout=30;User Id=sa;Password=P@ssword1;MultipleActiveResultSets=False;Timeout=30;
      - Bus__Host=rabbitmq://modular-monolith-rabbitmq
      - ASPNETCORE_URLS=http://+:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://modular-monolith-events-consumer/api/health-check"]
      retries: 5
  modular-monolith-api:
    build:
      context: "."
      dockerfile: "./docker/configuration/dotnet-api/Dockerfile"
      args:
        PROJECT_PATH: Example/ModularMonolith.API
        ASSEMBLY_NAME: ModularMonolith.API
    restart: on-failure
    depends_on:
      - "modular-monolith-database"
    environment:
      - ConnectionStrings__Database=Data Source=modular-monolith-database;Initial Catalog=Hexure;Connection Timeout=30;User Id=sa;Password=P@ssword1;MultipleActiveResultSets=False;Timeout=30;
      - Authority__Url=http://modular-monolith-identity
    ports:
      - 3004:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://modular-monolith-api/api/health-check"]
      retries: 5
