IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'registrations' AND  TABLE_NAME = 'Registration')
BEGIN
	CREATE TABLE [registrations].[Registration](
		[Id] UNIQUEIDENTIFIER NOT NULL,
		[Status] TINYINT NOT NULL,
		[CandidateFirstName] NVARCHAR(MAX) NOT NULL,
		[CandidateLastName] NVARCHAR(MAX) NOT NULL,
		[CandidateDateOfBirth] DATE NOT NULL
	 CONSTRAINT [PK_Registration] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
	) ON [PRIMARY]
END