IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'read' AND  TABLE_NAME = 'Subject')
BEGIN
	CREATE TABLE [read].[Subject](
        [Id] [bigint] NOT NULL,
        [Name] [nvarchar](50) NOT NULL,
     CONSTRAINT [PK_Subject] PRIMARY KEY CLUSTERED 
    (
        [Id] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
    ) ON [PRIMARY]
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'read' AND  TABLE_NAME = 'Location')
BEGIN
	CREATE TABLE [read].[Location](
        [Id] [bigint] NOT NULL,
        [Name] [nvarchar](50) NOT NULL,
     CONSTRAINT [PK_Location] PRIMARY KEY CLUSTERED 
    (
        [Id] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
    ) ON [PRIMARY]
END